dsa

diff --git a/.github/workflows/_create_prepare_aks_cluster.yml b/.github/workflows/_create_prepare_aks_cluster.yml
--- a/.github/workflows/_create_prepare_aks_cluster.yml
+++ b/.github/workflows/_create_prepare_aks_cluster.yml
@@ -85,13 +85,9 @@ jobs:
         run: |
           az aks get-credentials --name $CLUSTER_NAME --resource-group $RESOURCE_GROUP  --overwrite-existing
           export AKS_OIDC_ISSUER="$(az aks show -n $CLUSTER_NAME -g $RESOURCE_GROUP --query "oidcIssuerProfile.issuerUrl" -otsv)"
-          echo "Setting AKS_OIDC_ISSUER to $AKS_OIDC_ISSUER"
+          echo "Setting AKS_OIDC_ISSUER to $AKS_OIDC_ISSUER"\
 
-          export USER_ASSIGNED_CLIENT_ID="$(az identity show --resource-group $RESOURCE_GROUP --name $USER_ASSIGNED_IDENTITY_NAME --query 'clientId' -otsv)"
-          echo "Setting USER_ASSIGNED_CLIENT_ID to $USER_ASSIGNED_CLIENT_ID"
-
-          export MANAGED_IDENTITY="$(az identity show --resource-group $RESOURCE_GROUP --name $USER_ASSIGNED_IDENTITY_NAME --query 'id' -otsv)"
-          echo "Setting MANAGED_IDENTITY to $MANAGED_IDENTITY"
+          export APPLICATION_OBJECT_ID="$(az ad app list --display-name accct-aks-demos-builds-sp --query '[0].id' -otsv)"
 
           result=$(kubectl get namespace kafka 2>&1 || true)
           if [[ $result == *"not found"* ]]; then
@@ -107,24 +103,46 @@ jobs:
           kind: ServiceAccount 
           metadata: 
             annotations: 
-              azure.workload.identity/client-id: ${USER_ASSIGNED_CLIENT_ID} 
+              azure.workload.identity/client-id: cd2638ff-0fb5-4004-8bd3-e8a446785327
             name: workload-identity-sa
             namespace: kafka
           EOF
 
-          result=$(az identity federated-credential show --name myFedIdentity --identity-name $USER_ASSIGNED_IDENTITY_NAME --resource-group $RESOURCE_GROUP 2>&1 || true)
-          if [[ $result == *$AKS_OIDC_ISSUER* ]]; then
-              echo "Federated identity already exists"
-          else
-              echo "Federated identity not found. Creating... "
-              az identity federated-credential create --name myFedIdentity --identity-name $USER_ASSIGNED_IDENTITY_NAME --resource-group $RESOURCE_GROUP --issuer ${AKS_OIDC_ISSUER} --subject system:serviceaccount:${SERVICE_ACCOUNT_NAMESPACE}:${SERVICE_ACCOUNT_NAME} 
-          fi
+          cat <<EOF > params.json
+          {
+            "name": "kubernetes-federated-identity",
+            "issuer": "${AKS_OIDC_ISSUER}",
+            "subject": "system:serviceaccount:kafka:workload-identity-sa",
+            "description": "Kubernetes service account federated identity",
+            "audiences": [
+              "api://AzureADTokenExchange"
+            ]
+          }
+          EOF
 
-          kubectl create -f 'https://strimzi.io/install/latest?namespace=kafka' -n kafka 2>&1 || true 
-          # Apply the `Kafka` Cluster CR file
-          kubectl apply -f https://strimzi.io/examples/latest/kafka/kafka-persistent-single.yaml -n kafka 2>&1 || true 
+          az ad app federated-credential create --id $APPLICATION_OBJECT_ID --parameters params.json
 
-          echo "Sleep for 3 minute and wait for Kafka cluster to be created and fully working..."
-          sleep 180
+          # export USER_ASSIGNED_CLIENT_ID="$(az identity show --resource-group $RESOURCE_GROUP --name $USER_ASSIGNED_IDENTITY_NAME --query 'clientId' -otsv)"
+          # echo "Setting USER_ASSIGNED_CLIENT_ID to $USER_ASSIGNED_CLIENT_ID"
+
+          # export MANAGED_IDENTITY="$(az identity show --resource-group $RESOURCE_GROUP --name $USER_ASSIGNED_IDENTITY_NAME --query 'id' -otsv)"
+          # echo "Setting MANAGED_IDENTITY to $MANAGED_IDENTITY"
+
+          
+
+          # result=$(az identity federated-credential show --name myFedIdentity --identity-name $USER_ASSIGNED_IDENTITY_NAME --resource-group $RESOURCE_GROUP 2>&1 || true)
+          # if [[ $result == *$AKS_OIDC_ISSUER* ]]; then
+          #     echo "Federated identity already exists"
+          # else
+          #     echo "Federated identity not found. Creating... "
+          #     az identity federated-credential create --name myFedIdentity --identity-name $USER_ASSIGNED_IDENTITY_NAME --resource-group $RESOURCE_GROUP --issuer ${AKS_OIDC_ISSUER} --subject system:serviceaccount:${SERVICE_ACCOUNT_NAMESPACE}:${SERVICE_ACCOUNT_NAME} 
+          # fi
+
+          # kubectl create -f 'https://strimzi.io/install/latest?namespace=kafka' -n kafka 2>&1 || true 
+          # # Apply the `Kafka` Cluster CR file
+          # kubectl apply -f https://strimzi.io/examples/latest/kafka/kafka-persistent-single.yaml -n kafka 2>&1 || true 
+
+          # echo "Sleep for 3 minute and wait for Kafka cluster to be created and fully working..."
+          # sleep 180
 
 
