INTERESTING

diff --git a/.github/workflows/_create_prepare_aks_cluster.yml b/.github/workflows/_create_prepare_aks_cluster.yml
--- a/.github/workflows/_create_prepare_aks_cluster.yml
+++ b/.github/workflows/_create_prepare_aks_cluster.yml
@@ -74,7 +74,6 @@ jobs:
           # --workload-runtime KataCcIsolation \
           # --node-count 1 \
           # --generate-ssh-keys
-          echo "cluster-name=skr-kafka-demo-${RUN_ID}"
           echo "cluster-name=skr-kafka-demo-${RUN_ID}" >> $GITHUB_OUTPUT
 
       - name: Setup Workload Identity
@@ -82,50 +81,48 @@ jobs:
         env:
           CLUSTER_NAME: ${{ steps.create-aks-cluster.outputs.cluster-name}}
         run: |
-          echo "Cluster name is "
-          echo $CLUSTER_NAME
-          # az aks get-credentials --name $CLUSTER_NAME --resource-group $RESOURCE_GROUP  --overwrite-existing
-          # export AKS_OIDC_ISSUER="$(az aks show -n $CLUSTER_NAME -g $RESOURCE_GROUP --query "oidcIssuerProfile.issuerUrl" -otsv)"
-          # echo "Setting AKS_OIDC_ISSUER to $AKS_OIDC_ISSUER"
+          az aks get-credentials --name $CLUSTER_NAME --resource-group $RESOURCE_GROUP  --overwrite-existing
+          export AKS_OIDC_ISSUER="$(az aks show -n $CLUSTER_NAME -g $RESOURCE_GROUP --query "oidcIssuerProfile.issuerUrl" -otsv)"
+          echo "Setting AKS_OIDC_ISSUER to $AKS_OIDC_ISSUER"
 
-          # export USER_ASSIGNED_CLIENT_ID="$(az identity show --resource-group $RESOURCE_GROUP --name $USER_ASSIGNED_IDENTITY_NAME --query 'clientId' -otsv)"
-          # echo "Setting USER_ASSIGNED_CLIENT_ID to $USER_ASSIGNED_CLIENT_ID"
+          export USER_ASSIGNED_CLIENT_ID="$(az identity show --resource-group $RESOURCE_GROUP --name $USER_ASSIGNED_IDENTITY_NAME --query 'clientId' -otsv)"
+          echo "Setting USER_ASSIGNED_CLIENT_ID to $USER_ASSIGNED_CLIENT_ID"
 
-          # export MANAGED_IDENTITY="$(az identity show --resource-group $RESOURCE_GROUP --name $USER_ASSIGNED_IDENTITY_NAME --query 'id' -otsv)"
-          # echo "Setting MANAGED_IDENTITY to $MANAGED_IDENTITY"
+          export MANAGED_IDENTITY="$(az identity show --resource-group $RESOURCE_GROUP --name $USER_ASSIGNED_IDENTITY_NAME --query 'id' -otsv)"
+          echo "Setting MANAGED_IDENTITY to $MANAGED_IDENTITY"
 
-          # result=$(kubectl get namespace kafka 2>&1 || true)
-          # if [[ $result == *"not found"* ]]; then
-          #     echo "kafka namespace not found. Create kafka namespace..."
-          #     kubectl create namespace kafka
-          # else
-          #     echo "kafka namespace already exists."
-          # fi
+          result=$(kubectl get namespace kafka 2>&1 || true)
+          if [[ $result == *"not found"* ]]; then
+              echo "kafka namespace not found. Create kafka namespace..."
+              kubectl create namespace kafka
+          else
+              echo "kafka namespace already exists."
+          fi
 
-          # kubectl delete sa -n kafka workload-identity-sa 2>&1 || true
-          # cat <<EOF | kubectl apply -f - 
-          # apiVersion: v1 
-          # kind: ServiceAccount 
-          # metadata: 
-          #   annotations: 
-          #     azure.workload.identity/client-id: ${USER_ASSIGNED_CLIENT_ID} 
-          #   name: workload-identity-sa
-          #   namespace: kafka
-          # EOF
+          kubectl delete sa -n kafka workload-identity-sa 2>&1 || true
+          cat <<EOF | kubectl apply -f - 
+          apiVersion: v1 
+          kind: ServiceAccount 
+          metadata: 
+            annotations: 
+              azure.workload.identity/client-id: ${USER_ASSIGNED_CLIENT_ID} 
+            name: workload-identity-sa
+            namespace: kafka
+          EOF
 
-          # result=$(az identity federated-credential show --name myFedIdentity --identity-name $USER_ASSIGNED_IDENTITY_NAME --resource-group $RESOURCE_GROUP 2>&1 || true)
-          # if [[ $result == *$AKS_OIDC_ISSUER* ]]; then
-          #     echo "Federated identity already exists"
-          # else
-          #     echo "Federated identity not found. Creating... "
-          #     az identity federated-credential create --name myFedIdentity --identity-name $USER_ASSIGNED_IDENTITY_NAME --resource-group $RESOURCE_GROUP --issuer ${AKS_OIDC_ISSUER} --subject system:serviceaccount:${SERVICE_ACCOUNT_NAMESPACE}:${SERVICE_ACCOUNT_NAME} 
-          # fi
+          result=$(az identity federated-credential show --name myFedIdentity --identity-name $USER_ASSIGNED_IDENTITY_NAME --resource-group $RESOURCE_GROUP 2>&1 || true)
+          if [[ $result == *$AKS_OIDC_ISSUER* ]]; then
+              echo "Federated identity already exists"
+          else
+              echo "Federated identity not found. Creating... "
+              az identity federated-credential create --name myFedIdentity --identity-name $USER_ASSIGNED_IDENTITY_NAME --resource-group $RESOURCE_GROUP --issuer ${AKS_OIDC_ISSUER} --subject system:serviceaccount:${SERVICE_ACCOUNT_NAMESPACE}:${SERVICE_ACCOUNT_NAME} 
+          fi
 
-          # kubectl create -f 'https://strimzi.io/install/latest?namespace=kafka' -n kafka 2>&1 || true 
-          # # Apply the `Kafka` Cluster CR file
-          # kubectl apply -f https://strimzi.io/examples/latest/kafka/kafka-persistent-single.yaml -n kafka 2>&1 || true 
+          kubectl create -f 'https://strimzi.io/install/latest?namespace=kafka' -n kafka 2>&1 || true 
+          # Apply the `Kafka` Cluster CR file
+          kubectl apply -f https://strimzi.io/examples/latest/kafka/kafka-persistent-single.yaml -n kafka 2>&1 || true 
 
-          # echo "Sleep for 3 minute and wait for Kafka cluster to be created and fully working..."
-          # sleep 180
+          echo "Sleep for 3 minute and wait for Kafka cluster to be created and fully working..."
+          sleep 180
 
 
