test agina

diff --git a/.github/workflows/_deploy_kafka_test.yml b/.github/workflows/_deploy_kafka_test.yml
--- a/.github/workflows/_deploy_kafka_test.yml
+++ b/.github/workflows/_deploy_kafka_test.yml
@@ -59,12 +59,12 @@ jobs:
           repository: stevendongatmsft/confidential-container-demos
           path: confidential-container-demos
 
-      # - name: Log into Azure
-      #   run: |
-      #     az login --service-principal \
-      #       --username ${{ secrets.AZURE_SERVICE_PRINCIPAL_APP_ID }} \
-      #       --password ${{ secrets.AZURE_SERVICE_PRINCIPAL_PASSWORD }} \
-      #       --tenant ${{ secrets.AZURE_SERVICE_PRINCIPAL_TENANT }}
+      - name: Log into Azure
+        run: |
+          az login --service-principal \
+            --username ${{ secrets.AZURE_SERVICE_PRINCIPAL_APP_ID }} \
+            --password ${{ secrets.AZURE_SERVICE_PRINCIPAL_PASSWORD }} \
+            --tenant ${{ secrets.AZURE_SERVICE_PRINCIPAL_TENANT }}
             
       - name: Install Dependencies 
         id: install-dependencies 
@@ -72,21 +72,20 @@ jobs:
             curl -L https://github.com/a8m/envsubst/releases/download/v1.2.0/envsubst-`uname -s`-`uname -m` -o envsubst
             chmod +x envsubst
             sudo mv envsubst /usr/local/bin
-            envsubst
 
-            # result=$(az extension list -o table  2>&1 || true)
-            # if [[ $result == *"confcom"* ]]; then
-            #   echo "confcom already installed, upgrading confcom version."
-            #   az extension update --name confcom
-            # else
-            #   echo "confcom extension not found. Installing confcom..."
-            #   az extension add --name confcom
-            # fi
+            result=$(az extension list -o table  2>&1 || true)
+            if [[ $result == *"confcom"* ]]; then
+              echo "confcom already installed, upgrading confcom version."
+              az extension update --name confcom
+            else
+              echo "confcom extension not found. Installing confcom..."
+              az extension add --name confcom
+            fi
 
-            # curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
-            # chmod +x kubectl
-            # sudo mv kubectl /usr/local/bin
-            # kubectl version 2>&1 || true
+            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
+            chmod +x kubectl
+            sudo mv kubectl /usr/local/bin
+            kubectl version 2>&1 || true
 
       - name: Run Workload
         env:
@@ -97,9 +96,6 @@ jobs:
           RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP }} 
         id: run-workload
         run: | 
-          ls /usr/local/bin
-          which envsubst
-          /usr/local/bin/envsubst version 
 
           export CLUSTER_NAME=skr-kafka-demo-7127
           az aks get-credentials --name $CLUSTER_NAME --resource-group $RESOURCE_GROUP  --overwrite-existing
@@ -117,12 +113,10 @@ jobs:
           export SkrClientAKVEndpoint=$SkrClientAKVEndpoint
           echo "TOPIC value is: $TOPIC"
           export TOPIC=$TOPIC
-          envsubst version
+
           rm consumer-example.yaml 2>&1 || true 
-          cat consumer/consumer.yaml
-          echo "debugging"
-          ls 
-          envsubst <consumer/consumer.yaml> consumer-example.yaml -fail-fast
+          envsubst -i consumer/consumer.yaml -o consumer-exmaple.yaml
+          ls
           cat consumer-exmaple.yaml
           # export WORKLOAD_MEASUREMENT=$(az confcom katapolicygen -y consumer-example.yaml -j consumer/genpolicy-debug-settings.json --print-policy | base64 --decode | sha256sum | cut -d' ' -f1)
 
