enable setup workload identity

diff --git a/.github/workflows/_setup_workload_identity.yml b/.github/workflows/_setup_workload_identity.yml
--- a/.github/workflows/_setup_workload_identity.yml
+++ b/.github/workflows/_setup_workload_identity.yml
@@ -7,20 +7,12 @@ on:
         required: true
         type: string
         description: "Kubernetes version to use for AKS cluster creation"
-      cluster-name:
-        required: true
-        type: string
-        description: "Azure AKS Kubernetes Cluster Name"
   workflow_dispatch:
     inputs:
       kubernetes-version:
         required: true
         type: string
         description: "Kubernetes version to use for AKS cluster creation"
-      cluster-name:
-        required: true
-        type: string
-        description: "Azure AKS Kubernetes Cluster Name"
 
 
 jobs:
@@ -53,19 +45,20 @@ jobs:
           RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP }} 
           USER_ASSIGNED_IDENTITY_NAME: ${{ vars.USER_ASSIGNED_IDENTITY_NAME }}
           FEDERATED_IDENTITY_CREDENTIAL_NAME: ${{ vars.FEDERATED_IDENTITY_CREDENTIAL_NAME }}
-        run: | 
+        run: |
+          export CLUSTER_NAME=skr-kafka-demo-7127
           az aks get-credentials --name $CLUSTER_NAME --resource-group $RESOURCE_GROUP  --overwrite-existing
           export AKS_OIDC_ISSUER="$(az aks show -n $CLUSTER_NAME -g $RESOURCE_GROUP --query "oidcIssuerProfile.issuerUrl" -otsv)"
           echo "Setting AKS_OIDC_ISSUER to $AKS_OIDC_ISSUER"
 
-          export SUBSCRIPTION="$(az account show --query id --output tsv)" 
-          result=$(az identity show --name $USER_ASSIGNED_IDENTITY_NAME --resource-group $RESOURCE_GROUP --subscription "${SUBSCRIPTION}" 2>&1 || true)
-          if [[ $result == *"not found"* ]]; then
-              echo "Identity $USER_ASSIGNED_IDENTITY_NAME not found. Creating... "
-              az identity create --name $USER_ASSIGNED_IDENTITY_NAME --resource-group $RESOURCE_GROUP --location eastus --subscription "${SUBSCRIPTION}" 
-          else
-              echo Identity $USER_ASSIGNED_IDENTITY_NAME already exists. 
-          fi
+          # export SUBSCRIPTION="$(az account show --query id --output tsv)" 
+          # result=$(az identity show --name $USER_ASSIGNED_IDENTITY_NAME --resource-group $RESOURCE_GROUP --subscription "${SUBSCRIPTION}" 2>&1 || true)
+          # if [[ $result == *"not found"* ]]; then
+          #     echo "Identity $USER_ASSIGNED_IDENTITY_NAME not found. Creating... "
+          #     az identity create --name $USER_ASSIGNED_IDENTITY_NAME --resource-group $RESOURCE_GROUP --location eastus --subscription "${SUBSCRIPTION}" 
+          # else
+          #     echo Identity $USER_ASSIGNED_IDENTITY_NAME already exists. 
+          # fi
 
           export USER_ASSIGNED_CLIENT_ID="$(az identity show --resource-group $RESOURCE_GROUP --name $USER_ASSIGNED_IDENTITY_NAME --query 'clientId' -otsv)"
           echo "Setting USER_ASSIGNED_CLIENT_ID to $USER_ASSIGNED_CLIENT_ID"
